apiVersion: v1
kind: Service
metadata:
  name: hotstar-service
spec:
  selector:
    app: hotstar
    version: blue  # Switch this to "green" to direct traffic to the green deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
